### ISSUE TITLE
Product Logo Design

### ISSUE THREAD

**Issue by rjayanan** [cse110-fa22-group8/cse110-fa22-group8#31]
**What is the feature being added?**
Design a product logo for Frugal. 

**How will this feature be implemented?**
This feature will be implemented by turning it into an iso file and running it in main.js and in other html/css files. 

**Additional context**
The logo will serve as the desktop browser app logo and the logo will be displayed on various pages.

**Comment by rjayanan** [comment]
Logo Design is completed and available in png and svg format.

**Comment by kdandiwala** [comment]
Pivoted away from a desktop app - logo will not serve as the app logo but will remain on the web app. Logo resides on the starter branch.
